version: "3.8"
services:
  jenkins:
    build: .
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc_config:/var/jenkins_conf
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
volumes:
  jenkins_home:
